name: soft_cli
description: For creating custom flutter project from CBS Architecture. CBS Architecture https://github.com/webdastur/cbs_architecture
version: 2.0.0
homepage: https://github.com/webdastur/cbs_create



environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"


executables:
  cbs_create:

dependencies:
  path: ^1.8.3
  rename: ^2.1.1

  args: ^2.4.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

